name: PNPM Cache Example - Force 422

on:
  workflow_call:

jobs:
  install:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.20.4

    - name: Install PNPM
      run: npm install -g pnpm

    - name: Set invalid cache path
      id: invalid-path
      run: |
        # Setting a path that likely doesn't exist or isn't accessible to cause failure
        echo "store_path=/nonexistent/path/for/cache" >> $GITHUB_OUTPUT

    - name: Restore PNPM cache with invalid path
      uses: actions/cache@v4
      with:
        path: ${{ steps.invalid-path.outputs.store_path }}
        key: pnpm-store-invalid-key-!@#  # invalid characters to simulate error

    - name: Install dependencies
      run: pnpm install || echo "pnpm install failed as expected"

    - name: Save PNPM cache with invalid path
      uses: actions/cache@v4
      with:
        path: ${{ steps.invalid-path.outputs.store_path }}
        key: pnpm-store-invalid-key-!@#
