name: Reproduce Cache 422 Error

on:
  workflow_dispatch:

jobs:
  cache-422-repro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Restore PNPM cache (Path A)
        uses: actions/cache@v4
        with:
          path: /tmp/pnpm-store-path-A
          key: pnpm-store-Linux-18.20.4-v1

      - name: Show restored files
        run: ls -la /tmp/pnpm-store-path-A || echo "No cache restored"

      - name: Prepare different cache content in Path B
        run: |
          mkdir -p /tmp/pnpm-store-path-B
          echo "different dummy cache content" > /tmp/pnpm-store-path-B/cache.txt
          ls -la /tmp/pnpm-store-path-B

      - name: Save PNPM cache (Path B)
        uses: actions/cache@v4
        with:
          path: /tmp/pnpm-store-path-B
          key: pnpm-store-Linux-18.20.4-v1
