name: PNPM Cache 422 Repro

on:
  workflow_call:

jobs:
  repro-422:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Show PNPM store path A
        id: cache-path-A
        run: |
          mkdir -p /tmp/pnpm-store-A
          echo "dummy content A" > /tmp/pnpm-store-A/cache.txt
          echo "STORE_PATH=/tmp/pnpm-store-A" >> $GITHUB_ENV

      - name: Restore PNPM cache (Path A)
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-Linux-18.20.4-v1

      - name: Save PNPM cache (Path A)
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-Linux-18.20.4-v1

      - name: Show PNPM store path B
        id: cache-path-B
        run: |
          mkdir -p /tmp/pnpm-store-B
          echo "dummy content B" > /tmp/pnpm-store-B/cache.txt
          echo "STORE_PATH=/tmp/pnpm-store-B" >> $GITHUB_ENV

      - name: Save PNPM cache (Path B) - conflict expected
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-Linux-18.20.4-v1
