name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@mirror-url
        with:
          node-version: '20'
          mirrorURL: 'https://nodejs.org/dist/'
