name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '19'
          mirror-url: 'https://nodejs.org/dist/'
          check-latest : false
