name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: macos-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with empty node-version
      - name: Set up Node.js with different mirrorURL
        uses: marco-ippolito/setup-node@mirror
        #uses: actions/setup-node@v4
        with:
          node-version: '23'
          check-latest: true
          mirror-url: 'https://nodejs.org/download/release/'

