name: Test Setup Node with MirrorURL (Nightly Builds)

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: macos-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with nightly version and mirror URL
      - name: Set up Node.js (Nightly Build) with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '20'  # Specify nightly build version
          mirror-url: 'https://nodejs.org/dist/test'  # Use the nightly distribution URL
          check-latest: false   # Optional: Set to false to not check for the latest version
