name: PR134

on:
  
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: gowridurgad/setup-node@gowri-36
        with:
          node-version: 16
          architecture: "arm64"
          mirror-url : "https://nodejs.org/dist/"
