name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: macos-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with different mirror URL
      - name: Set up Node.js with different mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '18'  
          check-latest: false  
          mirror-url: 'https://nodejs.org/dist/'

