name: Reproduce npm ci hang

on:
  workflow_dispatch:

jobs:
  test-npm-ci-hang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Show node and npm versions
        run: |
          node --version
          npm --version

      - name: Run npm ci (watch for hang)
        run: npm ci
        timeout-minutes: 10
