name: Reproduce Cache Miss and Font Awesome Issue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with caching enabled (npm cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies (will log cache misses)
      - name: Install dependencies
        run: npm ci --verbose
        shell: bash

      # Step 4: Run tests (optional step, for example, to check that your app works)
      - name: Run tests
        run: npm test
        shell: bash
